[package]
name = "visualize_sort_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = { version = "0.5.1", features = ["egui"] }
rand = "0.8.5"
