[package]
name = "visualize-sort-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = { version = "0.5.1", features = ["egui"] }
rlua = "0.19.4"
